docs(editorial policy): add formatting rules
consta-design-system/portal pull request #52
Opened 2024-11-05 13:35 UTC by alyonurchick1

Closes #3760

2024-11-05 13:37 UTC, alyonurchick1 commented
@gizeasy хочу заменить пример компонента на какой-нибудь более простой и короткий. посмотри, пожалуйста, как выйдешь с больничного

2024-11-07 14:35 UTC, alyonurchick1 commented
@linturaven , посмотри, пожалуйста, получится ли переделать эту схему так, чтобы она красиво и не громоздко отображалась на портале. А то сейчас из-за того, что вертикально, всё место занимает на странице.
![image](https://github.com/user-attachments/assets/a107021f-3ee9-4151-b5aa-8f71cc3e4e8b)

2024-11-13 13:00 UTC, gizeasy requested changes

2024-11-13 13:00 UTC, gizeasy commented on src/docs/documentationStructure/documentationStructure.stand.mdx
> +В файле с раширением `.tsx` вы можете задать настройки раздела:
раширением -> расширением

2024-11-13 13:00 UTC, gizeasy commented on src/docs/documentationStructure/documentationStructure.stand.mdx
> +- [настройки раздела](#настройки-раздела) – файл с расширением `.tsx`.
Давай будем писать про расширение `.ts`. `.tsx` - используется в как обозначение `jsx` синтаксиса а в настройках его обычно нет. Просто сборка по может кушать и `.ts`, и`.tsx`. Но правельнее использовать `.ts`

2024-11-13 13:00 UTC, gizeasy commented on src/docs/documentationStructure/documentationStructure.stand.mdx
> +- `title` – название страницы. Оно будет отображаться вверху страницы в качестве заголовка H1.
Заголовок страницы

2024-11-13 13:00 UTC, gizeasy commented on src/docs/documentationStructure/documentationStructure.stand.mdx
> +- `description` – краткое описание содержимого страницы. Отображается на портале внизу названия страницы.
Отображается на портале внизу названия страницы. 
->
Отображается под заголовком страницы.

2024-11-13 13:00 UTC, gizeasy commented on src/docs/documentationStructure/documentationStructure.stand.mdx
> +- `title` – название страницы. Оно будет отображаться вверху страницы в качестве заголовка H1.
Заголовок

2024-11-13 13:00 UTC, gizeasy commented on src/docs/documentationStructure/documentationStructure.stand.mdx
> +import { createStand } from '##/stand/standConfig';
Кажется что не нужно спутывать понятия раздел, страница, группа.

createStand - создает страницу, страница может быть о компоненте а может в общем рассказывать о принципах(и т.п.)

Страница существует в группе, группа в библиотеке.

2024-11-13 13:00 UTC, gizeasy commented on src/docs/documentationStructure/documentationStructure.stand.mdx
> +## Страницы раздела
Вкладки страницы

2024-11-13 13:00 UTC, gizeasy commented on src/docs/documentationStructure/images/description.png
удали

2024-11-13 13:00 UTC, gizeasy commented on src/docs/documentationStructure/images/section.png
удали

2024-11-13 13:00 UTC, gizeasy commented on src/docs/documentationStructure/documentationStructure.stand.mdx
> +## Настройки раздела
ввести понятие стенда
раздел это стенд

 .stand.mdx - главная страница стенда
 dev.stand.mdx и прочие tab.stand.mdx - второстипеные страницы

2025-01-20 09:55 UTC, alyonurchick1 commented
мб не "предупреждение", а "важно"

2025-01-20 09:59 UTC, alyonurchick1 commented
https://refs-pull-52-merge---portal.consta.design/libs/portal/portal-formatting-rules?hash=%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%87%D0%B0%D0%BD%D0%B8%D0%B5  -сломалась верстка  в примечаниях

2025-01-20 10:04 UTC, alyonurchick1 commented
убрать блок "Заметки"

2025-05-27 13:52 UTC, merged